<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Str;
use App\Instructor;

class InstructorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $instructors = [
            [
                'name' => 'John Doe',
                'email' => 'john.doe@astechcommunity.com',
                'phone' => '+1-555-123-4567',
                'bio' => 'Senior Web Developer with 10+ years of experience in React, Node.js, and full-stack development.',
                'image' => 'instructors/john_doe.jpg',
                'specialization' => 'Web Development',
                'rating' => 4.8,
                'total_students' => 15000,
                'total_courses' => 12,
                'facebook' => 'https://facebook.com/johndoe',
                'twitter' => 'https://twitter.com/johndoe',
                'linkedin' => 'https://linkedin.com/in/johndoe',
                'is_active' => true,
            ],
            [
                'name' => 'Sarah Johnson',
                'email' => 'sarah.johnson@astechcommunity.com',
                'phone' => '+1-555-234-5678',
                'bio' => 'Digital Marketing Expert specializing in SEO, SEM, and social media marketing with 8 years of experience.',
                'image' => 'instructors/sarah_johnson.jpg',
                'specialization' => 'Digital Marketing',
                'rating' => 4.9,
                'total_students' => 12000,
                'total_courses' => 8,
                'facebook' => 'https://facebook.com/sarahjohnson',
                'twitter' => 'https://twitter.com/sarahjohnson',
                'instagram' => 'https://instagram.com/sarahjohnson',
                'linkedin' => 'https://linkedin.com/in/sarahjohnson',
                'is_active' => true,
            ],
            [
                'name' => 'Michael Chen',
                'email' => 'michael.chen@astechcommunity.com',
                'phone' => '+1-555-345-6789',
                'bio' => 'Data Scientist and AI Engineer with expertise in Python, Machine Learning, and Deep Learning frameworks.',
                'image' => 'instructors/michael_chen.jpg',
                'specialization' => 'Data Science',
                'rating' => 4.7,
                'total_students' => 8500,
                'total_courses' => 6,
                'twitter' => 'https://twitter.com/michaelchen',
                'linkedin' => 'https://linkedin.com/in/michaelchen',
                'is_active' => true,
            ],
            [
                'name' => 'Emily Davis',
                'email' => 'emily.davis@astechcommunity.com',
                'phone' => '+1-555-456-7890',
                'bio' => 'Creative Designer with 12 years of experience in branding, UI/UX design, and visual communications.',
                'image' => 'instructors/emily_davis.jpg',
                'specialization' => 'Graphic Design',
                'rating' => 4.8,
                'total_students' => 11000,
                'total_courses' => 10,
                'facebook' => 'https://facebook.com/emilydavis',
                'instagram' => 'https://instagram.com/emilydavis',
                'linkedin' => 'https://linkedin.com/in/emilydavis',
                'is_active' => true,
            ],
            [
                'name' => 'David Wilson',
                'email' => 'david.wilson@astechcommunity.com',
                'phone' => '+1-555-567-8901',
                'bio' => 'Business Consultant and Entrepreneur with 15 years of experience in startup development and business strategy.',
                'image' => 'instructors/david_wilson.jpg',
                'specialization' => 'Business',
                'rating' => 4.6,
                'total_students' => 9500,
                'total_courses' => 7,
                'facebook' => 'https://facebook.com/davidwilson',
                'twitter' => 'https://twitter.com/davidwilson',
                'linkedin' => 'https://linkedin.com/in/davidwilson',
                'is_active' => true,
            ],
            [
                'name' => 'Maria Rodriguez',
                'email' => 'maria.rodriguez@astechcommunity.com',
                'phone' => '+1-555-678-9012',
                'bio' => 'Microsoft Office Certified Expert with 12 years of experience in corporate training and productivity solutions.',
                'image' => 'instructors/maria_rodriguez.jpg',
                'specialization' => 'MS Office',
                'rating' => 4.9,
                'total_students' => 13500,
                'total_courses' => 15,
                'facebook' => 'https://facebook.com/mariarodriguez',
                'linkedin' => 'https://linkedin.com/in/mariarodriguez',
                'is_active' => true,
            ],
            [
                'name' => 'Ahmed Hassan',
                'email' => 'ahmed.hassan@astechcommunity.com',
                'phone' => '+1-555-789-0123',
                'bio' => 'Senior Frontend Developer and UI/UX Designer with expertise in modern web technologies and responsive design.',
                'image' => 'instructors/ahmed_hassan.jpg',
                'specialization' => 'Website Designing',
                'rating' => 4.8,
                'total_students' => 11200,
                'total_courses' => 18,
                'twitter' => 'https://twitter.com/ahmedhassan',
                'linkedin' => 'https://linkedin.com/in/ahmedhassan',
                'is_active' => true,
            ],
            [
                'name' => 'Jennifer Lee',
                'email' => 'jennifer.lee@astechcommunity.com',
                'phone' => '+1-555-890-1234',
                'bio' => 'Certified Public Accountant and Software Trainer specializing in accounting software and financial management systems.',
                'image' => 'instructors/jennifer_lee.jpg',
                'specialization' => 'Computerized Accounting',
                'rating' => 4.7,
                'total_students' => 8900,
                'total_courses' => 12,
                'facebook' => 'https://facebook.com/jenniferlee',
                'linkedin' => 'https://linkedin.com/in/jenniferlee',
                'is_active' => true,
            ],
            [
                'name' => 'Robert Kim',
                'email' => 'robert.kim@astechcommunity.com',
                'phone' => '+1-555-901-2345',
                'bio' => 'Computer Hardware Technician and System Administrator with 14 years of experience in hardware repair and maintenance.',
                'image' => 'instructors/robert_kim.jpg',
                'specialization' => 'Computer Hardware',
                'rating' => 4.6,
                'total_students' => 7800,
                'total_courses' => 10,
                'twitter' => 'https://twitter.com/robertkim',
                'linkedin' => 'https://linkedin.com/in/robertkim',
                'is_active' => true,
            ],
            [
                'name' => 'Lisa Thompson',
                'email' => 'lisa.thompson@astechcommunity.com',
                'phone' => '+1-555-012-3456',
                'bio' => 'Professional Video Editor and Motion Graphics Designer with expertise in Adobe Creative Suite and animation.',
                'image' => 'instructors/lisa_thompson.jpg',
                'specialization' => 'Video Editing',
                'rating' => 4.8,
                'total_students' => 10500,
                'total_courses' => 14,
                'instagram' => 'https://instagram.com/lisathompson',
                'linkedin' => 'https://linkedin.com/in/lisathompson',
                'is_active' => true,
            ],
            [
                'name' => 'Carlos Martinez',
                'email' => 'carlos.martinez@astechcommunity.com',
                'phone' => '+1-555-123-4567',
                'bio' => 'Mobile App Developer with expertise in React Native, Flutter, and native iOS/Android development.',
                'image' => 'instructors/carlos_martinez.jpg',
                'specialization' => 'Mobile App Development',
                'rating' => 4.7,
                'total_students' => 9200,
                'total_courses' => 11,
                'twitter' => 'https://twitter.com/carlosmartinez',
                'linkedin' => 'https://linkedin.com/in/carlosmartinez',
                'is_active' => true,
            ],
            [
                'name' => 'Dr. Ryan Scott',
                'email' => 'ryan.scott@astechcommunity.com',
                'phone' => '+1-555-234-5678',
                'bio' => 'Computer Science Professor and Programming Expert with 18 years of experience in software development and education.',
                'image' => 'instructors/ryan_scott.jpg',
                'specialization' => 'Programming Languages',
                'rating' => 4.9,
                'total_students' => 16800,
                'total_courses' => 22,
                'facebook' => 'https://facebook.com/ryanscott',
                'linkedin' => 'https://linkedin.com/in/ryanscott',
                'is_active' => true,
            ],
        ];

        foreach ($instructors as $instructor) {
            Instructor::updateOrCreate(
                ['email' => $instructor['email']], // Find by email
                $instructor
            );
        }
    }
}
